name: Continuous Deployment for my webapp

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Deploy application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_IP }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            # Deployment to a staging environment
            cd /home/ubuntu/
            sudo rm -rf sresh.net
            sudo git clone https://github.com/shreshkhatri/sresh.net.git
            cd /home/ubuntu/sresh.net
            if sudo docker inspect my_web_app &> /dev/null; then
              sudo docker stop my_web_app
              echo "Docker container stopped."
            else
              echo "Container 'my_web_app' does not exist or is not running."
            fi
            sudo docker build -t nextjs-docker .
            sudo docker -d run -p 80:80 --name my_web_app nextjs-docker
      - name: Notify Success
        if: success()
        run: |
          # Send a notification that deployment was successful
          echo "Deployment to production was successful."

      - name: Notify Failure
        if: failure()
        run: |
          # Send a notification that deployment failed
          echo "Deployment to production failed."
